{{- if eq .Values.certManager.enabled true }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer.name }} 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuer.name }}
    solvers:
    - http01:
        ingress:
          name: {{ include "medplum.fullname" . }}
{{- end }}