apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "medplum.serviceAccountName" . }}
  namespace: {{ include "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.medplumAzure }}
      {{- with .Values.medplumAzure.serviceAccount.annotations }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
    {{- if .Values.medplumGcp }}
      {{- with .Values.medplumGcp.serviceAccount.annotations }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
{{- if eq .Values.global.cloudProvider "gcp" }}
automountServiceAccountToken: true
{{- end }}
