# Default values for medplum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global: 
  cloudProvider: "gcp" # cloud providers options: "", gcp, azure 
  configSource:
    # Examples:
    # type: "env"
    # type: "aws:region:parameterName"
    # type: "gcp:projectId:secretId"
    # type: "azure:keyVaultURL:secretName"
    type: "env"  # Default to env

namespace: medplum

deployment:
  replicaCount: 1
  image:
    repository: medplum/medplum-server
    tag: latest
  env:
    # - name: SQL_DEBUG
    #   value: '*'
  resources:
    requests:
      memory: "1Gi"
    limits:
      memory: "2Gi"
  autoscaling:
    enabled: true
    targetCPUUtilizationPercentage: 80

service: {}

serviceAccount: {} 

ingress:
  deploy: true
  domain: [MY_DOMAIN] # Your domain name

#subchart dependencies
gcp:
  enabled: false
  
azure:
  enabled: false

certManager:
  enabled: true
  namespace: cert-manager
  clusterIssuer:
    name: "letsencrypt-test"
    tlsSecretName: "medplum-tls"
  certificate:
    name: "medplum-cert"
  ingress:
    hosts: "- api.zencore.medplum.dev"
