# Default values for medplum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  cloudProvider: azure

deployment:
  labels:
    azure.workload.identity/use: "true"
    
serviceAccount:
  annotations:
    azure.workload.identity/client-id: "your-id"